- setup.cfg
Add a setup.cfg for nose test.
> Add setup.cfg.

- .gitignore
- flask-supplier/server.py
- requirements.txt
Added py mongo as an object to the server.py file and added it to requirements.txt
> Adding py mongo

- flask-supplier/server.py
Added the code for the get route at /suppliers/supplierID
> Added the get route

- flask-supplier/service.py
I plan to use request function in flask
Like `request.args.get('supplier')` to implement query route
> queryRoute

- service/models.py
- service/service.py
> List Operation

- service/models.py
- service/service.py
Added a new Supplier class method called "get" that will get a supplier from db based on inputted supplier_id.
Then updated the service.py file to use that new method
> Add the find function that is the read operation

- service/service.py
Hi, I decide to write an action operation based on Greeson's idea. 
It will return a list of the best suppliers (averaging rating > 3.5) that supply the requested product.
> Create route for action operation

- service/service.py
Changes:
- Add route at /suppliers/supplierID with method DELETE
- returns supplier.delete passing the supplierID
> Add delete route

- service/service.py
- tests/suppliers_factory.py
- tests/test_service.py
- tests/test_suppliers.py
1. Writes model tests and service tests for Update.
2. Fix type error of ProductIdList in suppliers_factory.py.
> Writes model tests and service tests for Update.

- tests/test_service.py
- tests/test_suppliers.py
Writes models test and service test for DELETE.
> Writes models test and service test for DELETE.

- service/models.py
- service/service.py
It is an operation to return a list of suppliers (avgRating > 3) given a specific product id.
> Create an action operation

- service/service.py
Create a query operation. A user could query a supplier by their name
> create query operation router

- service/models.py
- service/service.py
- tests/test_service.py
Added a test case for:
1.  finding a valid supplier 
2. Finding a supplier that doesn't exist
> Add Read test case and Update read route

- tests/test_service.py
- tests/test_suppliers.py
Create test cases for query operation
> Create test cases for query operation

- service/models.py
- service/service.py
Invalid id and not-found query handling.
> Added id and not-found validation for multiple operations

- .coveragerc
This is a file that allows us to see what lines are not being covered. Too be removed at later point
> Add line-by-line coverage

- .coveragerc
- pylint.cfg
- pylint.conf
- service/__init__.py
- service/models.py
- service/service.py
- tests/test_service.py
- tests/test_suppliers.py
Scores for model.py/service.py/__init__.py improved from **-4.02/10** to over **9.0/10** (we need to hit at least **9.0/10**)
- **Usage**: cd /vagrant -> pylint --rcfile=pylint.conf <path_to>/<filename>
> Setup pylint.conf and improved model.py (still need more improvement)

- service/service.py
- tests/suppliers_factory.py
- tests/test_service.py
Fix 34, 40-42, 50-52, 60-62, 70-72, 133-134, 173, 179-182, 196, 212-219
service/service.py    85    2    98%   135-136
> Add tests of service

- service/service.py
Add condition checking:
```
if not isinstance(data,dict):
data = json.loads(data)
```
> Fix error raised in Create Op

- service/service.py
Added a additional return that has the location header in it.
> Add location header to return

- requirements.txt
Add codecov package in requirement.txt
> Add codecov in requirement.txt

- Procfile
- requirements.txt
Add honcho and gunicorn in requirement.txt
When running cmd line `honcho start &`, it will run the app in the background
> Add honcho in requirement.txt and add procfile

- Vagrantfile
- features/environment.py
- features/steps/supplier_steps.py
- features/suppliers.feature
Modified Vagrant file for PhantomJS
Add environment.py in feature directory to setup BDD test environment
Updated suppliers.feature to init database, visit the home page, and create a new supplier
Updated supplier_step.py for initializing, visiting the home page, and creating
> Setup BDD Environment and Implement Create Test

- tests/test_service.py
Although our app passed all the CI tests here and locally, I found the CI pipeline on IBM Cloud still failed.
It passed my local tests as usual, let's see if it fixes the problem on the cloud.
> Fix bugs for IBM Cloud pipeline tests

- service/models.py
- service/service.py
- service/static/index.html
- service/static/js/rest_api.js
- tests/test_service.py
- tests/test_suppliers.py
Create, Get by ID, and Delete operations are enabled, but there are some problems with return value to the textbox in the UI.
Query('Search' button) operation is returning the wrong values.
> modift UI for Create, Get and Delete.

- requirements.txt
The previous bug in IBM Cloud test pipeline has been fixed.
A new error arises in the deploy pipeline
Let's see if this fixes the problem on the cloud (again).
> Fix bugs in IBM Cloud deploy pipeline

- Vagrantfile
- service/service.py
Reverts nyu-devops-fall19-suppliers/suppliers#130
This merge made nosetests failing to respond.
> Revert "Update Vagrantfile to download and install the IBM Cloud CLI"

- Vagrantfile
**Bug description:**
Which is the main reason why nosetests are not responsed in https://github.com/nyu-devops-fall19-suppliers/suppliers/pull/143
Besides bug fixing, this push also reverts back to the functions based on https://github.com/nyu-devops-fall19-suppliers/suppliers/pull/130
> Hotfix DNS issue that causing db connection not working

- service/__init__.py
- service/service.py
- tests/test_service.py
I fixed the authorization error in the previous version. Now all test cases are passed with 96% coverage.
Besides, I also found in swagger API the update operation didn't display. I fixed this error. Now our page is like that
> Authorizations Checker & Fix Update Display Error 
